name: 'env-loader'
description: 'The .env file loader action that can be used in the GitHub workflow'
author: 'mixmoe'

inputs:
  file:
    required: false
    description: 'path to .env file'
    default: '.env'

  mask:
    required: false
    description: 'mask environment variable value'
    default: 'true'

runs:
  using: 'node12'
  main: 'dist/index.js'
